### ISSUE TITLE
Phase change (Boiling) does not occur in the flow boiling simulation unless nucleation site is provided

### ISSUE THREAD

**Issue by ssthakar** [fmuni/boilingFoam-PUBLIC#1]
I wanted to understand the requirements to model flow boiling using the icoBoiling solver. Do I  **need** to have a nucleation site (alpha.liquid = 0) to simulate boiling. Because If I don't provide it, no matter how high the temperature of the fluid region,  phase change or bubble formation simply does not occur.  Any guidance is greatly appreciated!
Thank you.

**Comment by MitchellWhiting** [comment]
Hi, I'm not part of the development team but yes you do need to provide a seed. The solver does have nucleation models that will generate that seed for you given certain conditions, I don't have any experience using these models but they are located in src/functionObjects/bubbleGenerator if you want to look at the code for them.

**Comment by ssthakar** [comment]
> Hi, I'm not part of the development team but yes you do need to provide a seed. The solver does have nucleation models that will generate that seed for you given certain conditions, I don't have any experience using these models but they are located in src/functionObjects/bubbleGenerator if you want to look at the code for them.

I went through the code regarding nucleation. To replicate realistic conditions where any site could be a nucleation site, is it feasible to pass in all the cell center locations of all wall cells (heated wall)? Thank you for your help!

**Comment by fmuni** [comment]
Hi @ssthakar (and @MitchellWhiting, thank you for jumping in!), sorry if I took some time to reply.

To answer the first question, yes: you __need__ to have a nucleation site (alpha.liquid = 0) in order to simulate boiling. This is because, in nature, phase transitions are initiated by perturbing an unstable state. As a result, current models for simulating boiling require the presence of an interface between phases, and therefore, if you initialize your simulation with alpha.liquid constant everywhere you are never going to see bubbles. This is why you need to complement the interface evaporation model with a nucleation model (or just initialize the simulation with small bubbles).

To the second question. In the latest [commit](https://github.com/fmuni/boilingFoam-PUBLIC/commit/d493a530965f4b71171a2d470fd59bec5c19c6d4), I added the new  [patchSites locationModel](https://github.com/fmuni/boilingFoam-PUBLIC/tree/master/src/functionObjects/bubbleGenerator/locationModels/patchSites). This model requires the patch name rather than the list of sites. I haven't tested it though, let me know if it works properly.
