### ISSUE TITLE
Parasitic currents in the stationary bubble

### ISSUE THREAD

**Issue by Bumble-7** [fmuni/boilingFoam-PUBLIC#2]
Hello everyone,
I am simulating the growth of bubbles at very small scales (micron scales). The main challenge I am facing is to reduce the spurious currents that are produced due to inaccuracy in the curvature calculation. I understand that using the smooth alpha field to calculate curvature can reduce these currents. But, I was not able to observed it in the results. To be specific, I am trying to simulate a stationary bubble of radius 30 micrometers. The velocities are in the range of 2.3 m/s. With time, the bubble gets drifted away, which is not desirable. 

I would like to know if such cases have been tested. If so, could you please let me know if there are any specific parameters that has to be employed. For example: curvature model, advector, smoothening cycles, reconstructive schemes and so on. 
Thanks

**Comment by fmuni** [comment]
Hi, 

Parasitic currents are always problematic, especially with small bubbles. Have you tried enabling __sigmaRhoCorrection__? That rebalances the surface tension based on the phase densities to concentrate it to the lower inertia phase.

**Comment by Bumble-7** [comment]
Hi, 
Yes, parasitic currents indeed become prominent as the length scale reduces. Were there any problems faced in the calculations related to microchannel heat transfer study? (https://www.sciencedirect.com/science/article/pii/S1359431123020689?via%3Dihub). How this problem was tackled? Is there any thumb rule or procedure that has been successful in reducing these currents?

I have indeed tried the density correction, and the results don't change. 

Thank you

**Comment by Bumble-7** [comment]
Hi, 
Can you share the information for the above query? The stability of tiny bubbles is still challenging due to these currents. It would be interesting to know how it was handled. 

Thank you in advance

**Comment by fmuni** [comment]
You trying to solve a problem this library was not designed for. When you have a boiling flow, the leading term in the pressure Poisson equation is the mass source term due to evaporation, not the surface tension force. At least for bubbles in your range of diameters, when the bubble becomes larger, the curvature of the interface becomes smaller and so does the surface tension force.

A single small bubble (tenths of microns) immersed in a fluid is an unstable problem for the VOF and I would suggest you look for a phase-field formulation instead.

**Comment by Bumble-7** [comment]
Thank you for your response.
