### ISSUE TITLE
Problem running simulation cases

### ISSUE THREAD

**Issue by LeeStr1** [fmuni/boilingFoam-PUBLIC#4]
All the simulation cases have problem creating mesh due to insufficient RAM on my system. Even though, I have allocated 50% of my computer's total RAM (16 GB). Everytime I run blockMesh or snappyHexMesh, the process gets killed in midway. 

I was able to run "nucleateBoiling_BuresSato" blockMesh by reducing the mesh size to 2.0*e-4 (which is originally  2.0*e-6 in the tutorial).

But, At the time of running the solver, I got the following error, "Cannot find file "points" in directory "heater/polyMesh" in times "0" down to constant". I guess, because of big mesh size, the heater cellZone can not be splitted. 

So, what can I do to solve this issue?

**Comment by fmuni** [comment]
Q: _All the simulation cases have problem creating mesh due to insufficient RAM on my system. Even though, I have allocated 50% of my computer's total RAM (16 GB). Everytime I run blockMesh or snappyHexMesh, the process gets killed in midway._

A: I don't know what to do about that, try buying a better computer. 

Q: _I was able to run "nucleateBoiling_BuresSato" blockMesh by reducing the mesh size to 2.0e-4 (which is originally 2.0e-6 in the tutorial)._

A: nucleateBoiling_BuresSato at full resolution works perfectly fine on my workstation using far less than 16GB of RAM.

Q: _But, At the time of running the solver, I got the following error, "Cannot find file "points" in directory "heater/polyMesh" in times "0" down to constant". I guess, because of big mesh size, the heater cellZone can not be splitted._

A: It means that the mesh was not created for whatever reason.

Q: _So, what can I do to solve this issue?_

A: If your issue is about memory in your computer, there is little I can do to help you.
